apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: replicator-deployment
  namespace: replicator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: replicator
    spec:
      serviceAccountName: replicator-account
      containers:
        - name: replicator
          image: zerospam/kubernetes-replicator:1.3
