kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: replicator-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: replicator-binding
roleRef:
  kind: ClusterRole
  name: replicator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: replicator-acccount
    namespace: replicator
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: replicator-account
  namespace: replicator